services:
  db:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 303304
      MYSQL_DATABASE: fotovoltaico
    ports:
      - "3307:3306"
 
  api:
    build:
      context: .
      dockerfile: Fotovoltaico/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db